variables:
  - &buildx_image "woodpeckerci/plugin-docker-buildx"
  - &platforms "linux/amd64"

pipeline:
  - name: Deploy to Docker Hub
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/redbeards-atis-generator
      dockerfile: Dockerfile
      platforms: *platforms
      tag: latest
    when:
      event: push

  - name: Deploy Tagged Version
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/redbeards-atis-generator
      dockerfile: Dockerfile
      platforms: *platforms
      tag: [latest, "${CI_COMMIT_TAG#v}"]
    when:
      event: tag

  - name: Deploy Pull Request
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/redbeards-atis-generator
      dockerfile: Dockerfile
      platforms: *platforms
      tag: pull_${CI_PULL_REQUEST}
    when:
      event: pull_request

branches: [main]
ignore_paths: [README.md, LICENSE, .github, .gitignore]
