name: Feature Request

about: Use this template to request a new feature or improvement to an existing feature

title: [Short description of the feature request]

labels:
  - feature request

body:
  ## Problem Description
  [Please describe the problem or pain point you are experiencing]

  ## Proposed Solution
  [Describe the solution you would like to see]

  ## Alternatives Considered
  [Describe any alternative solutions or features you've considered]

  ## Additional Context
  [Add any other context, information or screenshots about the feature request here]
